#ifndef SETTINGS_H
#define SETTINGS_H

#define NUMBEROFDIMENSIONS 2

#define NUMBEROFCELLSX 200
#define NUMBEROFCELLSY 200

#define WORKTIME 15

#define MAXNUMBEROFNEURONS 50
#define MAXNUMBEROFGROWTHCONES 16

#define INTERACTION00 ( 0.0 )
#define INTERACTION01 ( 1.0 )
#define INTERACTION10 ( 1.0 )
#define INTERACTION11 ( 0.0 )
#define NUMBEROFNEURONTYPES 2
//#define DIFFUSIONVISIBLE

//#define CLUI
#define GUI

//#define MEMORYCHECKING
//#define STEPBYSTEP
#define TRACESON
#define STATISTICSON

#define TRACEINFILE
//#define CELLSTACKTRACES
//#define GROWTHCONETRACES
#define CONNECTIONTRACES
//#define BRANCHINGTRACES

#define LENGTHSTATISTICS
#define ENVIRONMENTSTATISTICS
#define CONNECTIVITYGRAPHSTATISTICS

#define LOGFILENAME     "stat/log.txt"
#ifdef LENGTHSTATISTICS
#define LENGTHSTATISTICSFILE  "stat/length.txt"
#endif

#ifdef ENVIRONMENTSTATISTICS
#define ENVIRONMENTSTATISTICSFILE  "stat/environment.txt"
#endif

#ifdef CONNECTIVITYGRAPHSTATISTICS
#define CONNECTIVITYGRAPHSTATISTICSFILE  "stat/connectivitygraph.txt"
#define CONNECTIVITYGRAPHSTATISTICSRATE 5
#endif

#define AXONGROWTH
#define DENDRITEGROWTH
#endif