#ifndef SETTINGS_H
#define SETTINGS_H

#define NUMBEROFDIMENSIONS 2

#define NUMBEROFCELLSX 700
#define NUMBEROFCELLSY 700

#define WORKTIME 500

#define MAXNUMBEROFNEURONS 50
#define MAXNUMBEROFGROWTHCONES 16

#define INTERACTION00 ( 0.0 )
#define INTERACTION01 ( 1.0 )
#define INTERACTION10 ( 1.0 )
#define INTERACTION11 ( 0.0 )
#define NUMBEROFNEURONTYPES 2
//#define DIFFUSIONVISIBLE

//#define CLUI
#define GUI

//#define MEMORYCHECKING
//#define STEPBYSTEP
//#define TRACESON

#define TRACEINFILE
//#define CELLSTACKTRACES
//#define GROWTHCONETRACES
//#define CONNECTIONTRACES
//#define BRANCHINGTRACES

#define LOGFILENAME     "stat/log.txt"
//#define LENGTHSTATISTICS
#ifdef LENGTHSTATISTICS
#define LENGTHSTATISTICSFILE  "stat/length.txt"
#endif

//#define ENVIRONMENTSTATISTICS
#ifdef ENVIRONMENTSTATISTICS
#define ENVIRONMENTSTATISTICSFILE  "stat/environment.txt"
#endif

#define AXONGROWTH
#define DENDRITEGROWTH
#endif